export const SELECTORS = {
    basketRedCircle: '.basket-red-circle',
    searchContainerText: '.search-container-text',
    fanOfPictureContainer: '.fan-of-picture-container',
    resultSearchContainer: '.result-search-container',
    blackButton: '.black-button',
    blackButtonSearch: '.black-button-search',
    bestSellerBooks: '#best-seller-books',
    newReleases: '#new-releases',
    topRatedBooks: '#top-rated-books',
    ourSuggestion: '#our-suggestion',
    mostPopularBooks: '#most-popular-books',
    resultSearch: 'result-search',
    basket: '#basket',
    basketText: '.basket-text',
    subtotal: 'subtotal',
    shipping: 'shipping',
    total: 'total',
    urn: '.urn',
    basketOrderPromotion: '.basket-order-promotion',
    removeBook: '.remove-book',
    addBook: '.add-book',
    loader: '.loader',
    award: '.award',
    basketData: 'basket',
    tapeOfCardsContainer: '.tape-of-cards-container',
    dataBookID: 'data-book-id',
};