export const DataModule = (() => {
    const booksArray = [
        { 
            id: 1,
            title: 'Cooking Made Easy',
            author: 'Emily Clark',
            description: 'Simple and delicious recipes for everyday cooking.',
            price: 500.99,
            score: 4,
            img: "assets/Cooking Made Easy.png",
            categories: 'Best Seller Books',
        },
        {
            id: 2,
            title: 'Mystery of the Lost Island',
            author: 'Jane Smith',
            description: 'A gripping mystery novel that keeps you guessing till the end.',
            price: 14.99,
            score: 3,
            img: 'assets/Mystery of the Lost Island.png',
            categories: 'Best Seller Books',
        },
        {
            id: 3,
            title: 'Shadows of Doubt',
            author: 'Emma Watson',
            description: 'A detective novel filled with twists and unexpected turns.',
            price: 13.99,
            score: 3,
            img: 'assets/Shadows of Doubt.png',
            categories: 'Best Seller Books',
        },
        {
            id: 4,
            title: 'Taste of Italy',
            author: 'Gina Rossi',
            description: 'Authentic Italian recipes to bring the flavors of Italy home.',
            price: 15.75,
            score: 4,
            img: 'assets/Taste of Italy.png',
            categories: 'Best Seller Books',
        },
        {
            id: 5,
            title: 'Echoes of the Past',
            author: 'Michael Brown',
            description: 'A historical tale unraveling secrets buried in time.',
            price: 17.50,
            score: 5,
            img: 'assets/Echoes of the Past.png',
            categories: 'Best Seller Books',
        },
        {
            id: 6,
            title: 'The Lost Expedition',
            author: 'Tom Hardy',
            description: 'An adventurer’s perilous quest in the Amazon jungle.',
            price: 18.25,
            score: 4,
            img: 'assets/The Lost Expedition.png',
            categories: 'New Releases',
        },
        {
            id: 7,
            title: 'Taste of Italy',
            author: 'Gina Rossi',
            description: 'Authentic Italian recipes to bring the flavors of Italy home.',
            price: 15.75,
            score: 4,
            img: 'assets/Taste of Italy.png',
            categories: 'New Releases',
        },
        {
            id: 8,
            title: 'Learning React',
            author: 'Alex Johnson',
            description: 'A comprehensive guide to mastering React.js and modern web development.',
            price: 29.99,
            score: 5,
            img: 'assets/Learning React.png',
            categories: 'New Releases',
        },
        {
            id: 9,
            title: 'The Silent Forest',
            author: 'David Kim',
            description: 'A chilling suspense story set in a haunted woodland.',
            price: 12.99,
            score: 3,
            img: 'assets/The Silent Forest.png',
            categories: 'New Releases',
        },
        {
            id: 10,
            title: 'Mystery of the Lost Island',
            author: 'Jane Smith',
            description: 'A gripping mystery novel that keeps you guessing till the end.',
            price: 14.99,
            score: 3,
            img: 'assets/Mystery of the Lost Island.png',
            categories: 'New Releases',
        }
    ];
    
    const getBooks = () => booksArray;
    return { getBooks };
})();